// examples/nuxt/app/pages/checkout/[id].vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import {
  buildPaymentUri,
  clearConfirming,
  confirmingExplorerUrl,
  getConfirming,
  isOpenStatus,
  isWalletPayable,
  remainingMs,
  resolveRedirectUrl,
  watchCheckoutEvents,
} from '@klappay/checkout-kit/client'
import type { CheckoutPayload, ConfirmingRecord } from '@klappay/checkout-kit/client'

const route = useRoute()
const chargeId = route.params.id as string

const { data: payload, error: fetchError } = await useFetch<CheckoutPayload>(`/api/checkout/${chargeId}`)

const confirming = ref<ConfirmingRecord | null>(null)
let stopWatching: (() => void) | null = null

function applyPayload(updated: CheckoutPayload) {
  payload.value = updated

  if (isOpenStatus(updated.status)) return

  stopWatching?.()
  clearConfirming(updated.id)
  confirming.value = null

  if (updated.status === 'confirmed') {
    const url = resolveRedirectUrl(updated.redirectUrl)
    if (url) window.location.href = url
  }
}

onMounted(() => {
  confirming.value = getConfirming(chargeId)
  stopWatching = watchCheckoutEvents(`/api/checkout/${chargeId}/events`, applyPayload)
})

onUnmounted(() => {
  stopWatching?.()
})

function onSent(txHash: string) {
  confirming.value = getConfirming(chargeId)
  console.log('sent', txHash)
}
</script>

<template>
  <main style="max-width: 32rem; margin: 4rem auto; font-family: sans-serif; padding: 0 1rem">
    <h1>Checkout {{ chargeId }}</h1>

    <p v-if="fetchError">Could not load this charge ({{ fetchError.message }}).</p>

    <template v-else-if="payload">
      <p>
        {{ payload.amount }} {{ payload.currency }} &mdash; status:
        <strong>{{ payload.status }}</strong>
      </p>

      <p v-if="confirming">
        Confirming on {{ confirming.network }}, {{ Math.max(0, Math.round(remainingMs(confirming) / 1000)) }}s
        left.
        <a v-if="confirmingExplorerUrl(confirming)" :href="confirmingExplorerUrl(confirming)!" target="_blank">
          View transaction
        </a>
      </p>

      <div v-for="option in payload.paymentOptions" :key="`${option.token}-${option.network}`">
        <template v-if="isWalletPayable(option)">
          <WalletPaymentButton :option="option" :address="payload.address" :charge-id="payload.id" @sent="onSent" />
          <p style="color: #666; font-size: 0.85em; margin-top: -0.5rem">
            QR fallback: <code>{{ buildPaymentUri(option, payload.address) }}</code>
          </p>
        </template>
        <div v-else style="border: 1px dashed #ccc; border-radius: 0.5rem; padding: 1rem; margin-bottom: 1rem">
          <p>
            Send <strong>{{ option.token }}</strong> on <strong>{{ option.network }}</strong> directly to:
          </p>
          <code>{{ payload.address }}</code>
          <p style="color: #666; font-size: 0.9em">
            No wallet chain mapping for this pair yet — still payable by sending to the address above
            directly (or via QR).
          </p>
        </div>
      </div>

      <template v-if="payload.swapAlternatives.length > 0">
        <h2>Pay with a different crypto</h2>
        <SwapPaymentButton
          v-for="alt in payload.swapAlternatives"
          :key="`${alt.token}-${alt.network}`"
          :alt="alt"
          :charge-id="payload.id"
        />
      </template>
    </template>

    <p v-else>Loading…</p>
  </main>
</template>

// examples/sveltekit/src/routes/checkout/[id]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { Writable } from 'svelte/store'
  import {
    buildPaymentUri,
    clearConfirming,
    confirmingExplorerUrl,
    getConfirming,
    isOpenStatus,
    isWalletPayable,
    remainingMs,
    resolveRedirectUrl,
    saveConfirming,
    watchCheckoutEvents,
  } from '@klappay/checkout-kit/client'
  import type { CheckoutPayload, ConfirmingRecord, PaymentOption, WalletStatus } from '@klappay/checkout-kit/client'
  import { createWalletStore } from '$lib/wallet-store'
  import SwapAlternatives from './SwapAlternatives.svelte'
  import type { PageData } from './$types'

  export let data: PageData

  let payload: CheckoutPayload = data.payload
  let confirming: ConfirmingRecord | null = getConfirming(payload.id)

  const walletOptions = payload.paymentOptions.filter(isWalletPayable)
  const manualOptions = payload.paymentOptions.filter((option) => !isWalletPayable(option))
  const primaryOption: PaymentOption | null = walletOptions[0] ?? null

  let account: Writable<string | null> | null = null
  let status: Writable<WalletStatus> | null = null
  let txHash: Writable<string | null> | null = null
  let walletError: Writable<unknown> | null = null
  let connect: (() => Promise<string> | undefined) | null = null
  let pay: (() => Promise<string> | undefined) | null = null

  if (primaryOption) {
    const store = createWalletStore(primaryOption, payload.address)
    account = store.account
    status = store.status
    txHash = store.txHash
    walletError = store.error
    connect = store.connect
    pay = store.pay
  }

  onMount(() => {
    const unsubscribe = txHash?.subscribe((hash) => {
      if (!hash || !primaryOption) return
      saveConfirming(payload.id, primaryOption.network, hash)
      confirming = getConfirming(payload.id)
    })

    const stopWatching = watchCheckoutEvents(`/api/checkout/${payload.id}/events`, (updated) => {
      payload = updated

      if (isOpenStatus(updated.status)) return

      stopWatching()
      clearConfirming(updated.id)
      confirming = null

      if (updated.status === 'confirmed') {
        const redirect = resolveRedirectUrl(updated.redirectUrl)
        if (redirect) window.location.href = redirect
      }
    })

    return () => {
      unsubscribe?.()
      stopWatching()
    }
  })
</script>

<svelte:head>
  <title>Checkout {payload.id}</title>
</svelte:head>

<main>
  <h1>Checkout {payload.id}</h1>
  <p>Status: <strong>{payload.status}</strong></p>
  <p>
    Amount: {payload.amount}
    {payload.currency}
  </p>

  {#if confirming}
    <div class="confirming">
      <p>Waiting for confirmation on {confirming.network}…</p>
      <p>{Math.max(0, Math.round(remainingMs(confirming) / 1000))}s left</p>
      {#if confirmingExplorerUrl(confirming)}
        <a href={confirmingExplorerUrl(confirming) ?? undefined} target="_blank" rel="noreferrer">
          View on block explorer
        </a>
      {/if}
    </div>
  {/if}

  {#if primaryOption && account && status && connect && pay}
    <section>
      <h2>Pay with wallet</h2>
      <p>
        {primaryOption.token} on {primaryOption.network}
      </p>
      {#if !$account}
        <button type="button" on:click={connect}>Connect wallet</button>
      {:else}
        <button type="button" on:click={pay} disabled={$status === 'paying'}>
          {$status === 'paying' ? 'Confirm in wallet…' : 'Pay now'}
        </button>
      {/if}
      {#if $txHash}
        <p>Sent: {$txHash}</p>
      {/if}
      {#if $walletError}
        <p class="error">Wallet error: {String($walletError)}</p>
      {/if}
      <p class="uri">{buildPaymentUri(primaryOption, payload.address)}</p>
    </section>
  {/if}

  <SwapAlternatives chargeId={payload.id} swapAlternatives={payload.swapAlternatives} />

  {#if manualOptions.length > 0}
    <section>
      <h2>Pay manually</h2>
      <p>No wallet mapping for these — send directly to the address below:</p>
      {#each manualOptions as option (option.token + option.network)}
        <p>
          {option.token} on {option.network}: <code>{payload.address}</code>
        </p>
      {/each}
    </section>
  {/if}
</main>

<style>
  main {
    max-width: 32rem;
    margin: 2rem auto;
    padding: 0 1rem;
    font-family: system-ui, sans-serif;
  }

  section {
    margin-top: 1.5rem;
    padding-top: 1rem;
    border-top: 1px solid #ddd;
  }

  .confirming {
    margin-top: 1rem;
    padding: 0.75rem;
    background: #fffbe6;
    border: 1px solid #f0d878;
    border-radius: 0.25rem;
  }

  .uri {
    word-break: break-all;
    font-size: 0.8rem;
    color: #666;
  }

  .error {
    color: #b00020;
  }
</style>
